// src/Chat.vue
<script setup>
import CCDraw from "./components/CCDraw.vue";
</script>
<template>
  <div class="flex flex-col h-screen bg-gray-100">
    <!-- Header -->
    <header class="h-16 bg-white shadow flex items-center justify-between px-6">
      <h1 class="text-lg font-bold text-gray-700">Chat Room</h1>
      <div class="flex items-center space-x-4">
        <button class="bg-blue-500 text-white px-4 py-2 rounded text-sm">
          Start Meeting
        </button>
      </div>
    </header>

    <!-- Main content (chat area and input field) -->
    <div class="flex flex-grow overflow-hidden">
      <!-- Chat Area -->
      <main class="flex-grow bg-white p-6 overflow-y-scroll">
        <!-- User 1 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
              alt="User 1 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
          </div>
          <p class="bg-gray-100 rounded p-2 inline-block">
            Hello, how are you?
          </p>
        </div>
        <!-- User 2 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
              alt="User 2 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
          </div>
          <CCDraw />
        </div>

        <!-- User 2 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
              alt="User 2 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
          </div>
          <img
            class="w-48 h-32 object-cover rounded"
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
            alt="Media Message"
          />
        </div>

        <!-- User 3 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
              alt="User 3 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
          </div>
          <pre
            class="bg-gray-800 text-white p-2 rounded"
          ><code>// Some code here</code></pre>
        </div>

        <!-- User 1 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
              alt="User 1 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
          </div>
          <a href="#" class="text-blue-500">file.txt</a>
        </div>

        <!-- User 2 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
              alt="User 2 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
          </div>
          <p class="bg-gray-100 rounded p-2 inline-block">👋</p>
        </div>

        <!-- User 3 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
              alt="User 3 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
          </div>
          <h3 class="text-lg font-bold">This is a Heading</h3>
        </div>

        <!-- User 1 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
              alt="User 1 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
          </div>
          <div class="rounded shadow-lg p-4 bg-white">
            <h3 class="font-bold text-xl mb-2">Card Title</h3>
            <p>
              Card content goes here. It could be a brief about an article, a
              task, etc.
            </p>
          </div>
        </div>

        <!-- User 2 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
              alt="User 2 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
          </div>
          <ul class="list-disc list-inside">
            <li>Item 1</li>
            <li>Item 2</li>
            <li>Item 3</li>
          </ul>
        </div>

        <!-- User 3 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
              alt="User 3 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
          </div>
          <table class="table-auto">
            <thead>
              <tr>
                <th class="px-4 py-2">Title</th>
                <th class="px-4 py-2">Author</th>
                <th class="px-4 py-2">Views</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="border px-4 py-2">Intro to CSS</td>
                <td class="border px-4 py-2">John Doe</td>
                <td class="border px-4 py-2">858</td>
              </tr>
              <tr class="bg-gray-100">
                <td class="border px-4 py-2">A Guide to Flexbox</td>
                <td class="border px-4 py-2">Jane Smith</td>
                <td class="border px-4 py-2">231</td>
              </tr>
              <tr>
                <td class="border px-4 py-2">Learning JavaScript</td>
                <td class="border px-4 py-2">Michael Johnson</td>
                <td class="border px-4 py-2">655</td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- User 1 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
              alt="User 1 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
          </div>
          <div class="p-4 bg-white rounded shadow">
            <h3 class="font-bold text-xl mb-2">Blog Title</h3>
            <p>First few lines of the blog content...</p>
            <a href="#" class="text-blue-500">Read more</a>
          </div>
        </div>

        <!-- User 2 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
              alt="User 2 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
          </div>
          <div class="p-4 bg-white rounded shadow">
            <h3 class="font-bold text-xl mb-2">Meeting: Team Standup</h3>
            <p>Date: 23rd June 2023</p>
            <p>Time: 10:00 AM - 10:30 AM</p>
          </div>
        </div>

        <!-- User 3 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
              alt="User 3 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
          </div>
          <div class="border p-4 rounded">
            <h3 class="font-bold text-lg mb-2">Task Title</h3>
            <p class="text-sm text-gray-700 mb-2">Task description...</p>
            <span
              class="inline-block bg-green-200 text-green-800 px-2 py-1 rounded text-sm"
              >To Do</span
            >
          </div>
        </div>

        <!-- User 1 Chat Message -->
        <div class="mb-4">
          <div class="flex items-center">
            <img
              src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
              alt="User 1 Avatar"
              class="w-8 h-8 rounded-full"
            />
            <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
          </div>
          <div class="border p-4 rounded">
            <h3 class="font-bold text-lg mb-2">Project Timeline</h3>
            <div class="h-2 bg-gray-200 rounded">
              <div class="h-2 bg-blue-500 rounded" style="width: 50%"></div>
            </div>
            <p class="text-sm text-gray-700 mt-2">50% completed</p>
          </div>
        </div>
      </main>

      <!-- Message Input Field -->
      <footer
        class="h-16 bg-white border-t border-gray-200 flex items-center px-4"
      >
        <input
          class="flex-grow h-10 px-4 py-2 border rounded"
          type="text"
          placeholder="Type your message here..."
        />
        <button class="bg-blue-500 text-white px-4 py-2 rounded ml-2">
          Send
        </button>
      </footer>
    </div>
  </div>
</template>

// apps/aregridjs/src/app/chat/chat.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'aregrid-chat',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.scss'],
})
export class ChatComponent {}

<div class="flex flex-col h-screen bg-gray-100">
  <!-- Header -->
  <header class="h-32 shadow flex items-center justify-between px-6">
    <h1 class="text-lg font-bold text-gray-700">Chat Room</h1>
    <div class="flex items-center space-x-4">
      <button class="bg-blue-500 text-white px-4 py-2 rounded text-sm">
        Start Meeting
      </button>
    </div>
  </header>

  <!-- Main content (chat area and input field) -->
  <div class="flex flex-grow overflow-hidden">
    <!-- Message Input Field -->
    <!-- Chat Area -->
    <main class="flex-grow p-6 overflow-y-scroll">
      <!-- User 1 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
            alt="User 1 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
        </div>
        <p class="bg-gray-100 rounded p-2 inline-block">Hello, how are you?</p>
      </div>
      <!-- User 2 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
            alt="User 2 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
        </div>
        <!-- <CCDraw /> -->
      </div>

      <!-- User 2 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
            alt="User 2 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
        </div>
        <img
          class="w-48 h-32 object-cover rounded"
          src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
          alt="Media Message"
        />
      </div>

      <!-- User 3 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
            alt="User 3 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
        </div>
        <pre
          class="bg-gray-800 text-white p-2 rounded"
        ><code>// Some code here</code></pre>
      </div>

      <!-- User 1 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
            alt="User 1 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
        </div>
        <a href="#" class="text-blue-500">file.txt</a>
      </div>

      <!-- User 2 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
            alt="User 2 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
        </div>
        <p class="bg-gray-100 rounded p-2 inline-block">👋</p>
      </div>

      <!-- User 3 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
            alt="User 3 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
        </div>
        <h3 class="text-lg font-bold">This is a Heading</h3>
      </div>

      <!-- User 1 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
            alt="User 1 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
        </div>
        <div class="rounded shadow-lg p-4 bg-white">
          <h3 class="font-bold text-xl mb-2">Card Title</h3>
          <p>
            Card content goes here. It could be a brief about an article, a
            task, etc.
          </p>
        </div>
      </div>

      <!-- User 2 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
            alt="User 2 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
        </div>
        <ul class="list-disc list-inside">
          <li>Item 1</li>
          <li>Item 2</li>
          <li>Item 3</li>
        </ul>
      </div>

      <!-- User 3 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
            alt="User 3 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
        </div>
        <table class="table-auto">
          <thead>
            <tr>
              <th class="px-4 py-2">Title</th>
              <th class="px-4 py-2">Author</th>
              <th class="px-4 py-2">Views</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="border px-4 py-2">Intro to CSS</td>
              <td class="border px-4 py-2">John Doe</td>
              <td class="border px-4 py-2">858</td>
            </tr>
            <tr class="bg-gray-100">
              <td class="border px-4 py-2">A Guide to Flexbox</td>
              <td class="border px-4 py-2">Jane Smith</td>
              <td class="border px-4 py-2">231</td>
            </tr>
            <tr>
              <td class="border px-4 py-2">Learning JavaScript</td>
              <td class="border px-4 py-2">Michael Johnson</td>
              <td class="border px-4 py-2">655</td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- User 1 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
            alt="User 1 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
        </div>
        <div class="p-4 bg-white rounded shadow">
          <h3 class="font-bold text-xl mb-2">Blog Title</h3>
          <p>First few lines of the blog content...</p>
          <a href="#" class="text-blue-500">Read more</a>
        </div>
      </div>

      <!-- User 2 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/0077f8c11bd1f32199710a0259c9873ce8e7b63b_full.jpg"
            alt="User 2 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Jane Smith</h2>
        </div>
        <div class="p-4 bg-white rounded shadow">
          <h3 class="font-bold text-xl mb-2">Meeting: Team Standup</h3>
          <p>Date: 23rd June 2023</p>
          <p>Time: 10:00 AM - 10:30 AM</p>
        </div>
      </div>

      <!-- User 3 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/35/35547e0ab2d4ff89ed4d1b5347f2ec27170ee224_full.jpg"
            alt="User 3 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">Michael Johnson</h2>
        </div>
        <div class="border p-4 rounded">
          <h3 class="font-bold text-lg mb-2">Task Title</h3>
          <p class="text-sm text-gray-700 mb-2">Task description...</p>
          <span
            class="inline-block bg-green-200 text-green-800 px-2 py-1 rounded text-sm"
            >To Do</span
          >
        </div>
      </div>

      <!-- User 1 Chat Message -->
      <div class="mb-4">
        <div class="flex items-center">
          <img
            src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/00/005099b73f79ca48a6acf026c0021f93f323e9ba_full.jpg"
            alt="User 1 Avatar"
            class="w-8 h-8 rounded-full"
          />
          <h2 class="font-bold text-gray-800 ml-2">John Doe</h2>
        </div>
        <div class="border p-4 rounded">
          <h3 class="font-bold text-lg mb-2">Project Timeline</h3>
          <div class="h-2 bg-gray-200 rounded">
            <div class="h-2 bg-blue-500 rounded" style="width: 50%"></div>
          </div>
          <p class="text-sm text-gray-700 mt-2">50% completed</p>
        </div>
      </div>
    </main>

    <footer class="h-16 border-t border-gray-200 flex items-center px-4">
      <input
        class="flex-grow h-10 px-4 py-2 border rounded"
        type="text"
        placeholder="Type your message here..."
      />
      <button class="bg-blue-500 text-white px-4 py-2 rounded ml-2">
        Send
      </button>
    </footer>
  </div>
</div>
